// Fake NDA contract used as pipeline input.

export const sampleContract = {
  title: "Mutual Non-Disclosure Agreement",
  parties: ["Meridian Legal Group", "Apex Technologies Inc."],
  date: "2026-02-15",
  rawText: [
    "MUTUAL NON-DISCLOSURE AGREEMENT",
    "",
    "This Mutual Non-Disclosure Agreement ('Agreement') is entered into as of February 15, 2026,",
    "by and between Meridian Legal Group ('Party A') and Apex Technologies Inc. ('Party B').",
    "",
    "1. DEFINITION OF CONFIDENTIAL INFORMATION",
    "Confidential Information means any data or information, oral or written, disclosed by either",
    "party that is designated as confidential or that reasonably should be understood to be",
    "confidential given the nature of the information and the circumstances of disclosure.",
    "",
    "2. OBLIGATIONS OF RECEIVING PARTY",
    "The Receiving Party shall hold and maintain the Confidential Information in strict confidence",
    "for the sole and exclusive benefit of the Disclosing Party. The Receiving Party shall not,",
    "without prior written approval, use for its own benefit, publish, copy, or otherwise disclose",
    "to others, or permit the use by others for their benefit, any Confidential Information.",
    "",
    "3. TIME PERIOD",
    "The nondisclosure provisions of this Agreement shall survive the termination of this Agreement",
    "and the Receiving Party's duty to hold Confidential Information in confidence shall remain in",
    "effect until the Confidential Information no longer qualifies as a trade secret or until the",
    "Disclosing Party sends written notice releasing the Receiving Party from this Agreement,",
    "whichever occurs first. This Agreement shall be binding for a period of five (5) years.",
    "",
    "4. NON-SOLICITATION",
    "During the term of this Agreement and for a period of two (2) years thereafter, neither party",
    "shall directly or indirectly solicit or attempt to solicit any employee, contractor, or",
    "consultant of the other party.",
    "",
    "5. REMEDIES",
    "The parties acknowledge that any breach of this Agreement may cause irreparable harm and that",
    "monetary damages may be insufficient. The non-breaching party shall be entitled to seek",
    "injunctive relief in addition to any other remedies available at law or in equity.",
    "The breaching party shall be liable for all attorneys' fees and costs incurred in enforcement",
    "with no cap on liability.",
    "",
    "6. GOVERNING LAW",
    "This Agreement shall be governed by and construed in accordance with the laws of the State of",
    "Delaware, without regard to its conflict of laws provisions. Any disputes shall be resolved",
    "exclusively in the courts of Delaware.",
  ].join("\n"),
};
